baseURL = "http://localhost:1313/"
languageCode = 'en-us'
title = '如水沉香'
theme = "hugo-theme-stack"

[params]
  [params.sidebar]
    avatar = "img/avatar.png"

  [params.widgets]
  # 首页侧边栏
    homepage = [
      { type = "categories", params = { limit = 10 } },
      { type = "tag-cloud", params = { limit = 10 } },
    ]
  # 文章页侧边栏
    page = [
      { type = "toc" }
    ]