baseURL = "http://localhost:1313/"
languageCode = 'en-us'
title = '如水沉香'
theme = "hugo-theme-stack"

[params]
  [params.sidebar]
    avatar = "img/avatar.png"

  [params.widgets]
  # 首页侧边栏
    homepage = [
      { type = "categories", params = { limit = 10 } },
      { type = "tag-cloud", params = { limit = 10 } },
    ]
  # 文章页侧边栏
    page = [
      { type = "toc" }
    ]
  
[markup]
  [markup.tableOfContents]
    startLevel = 2      # 从一级标题开始（可选，默认是2）
    endLevel = 4        # 关键：结束层级改为4，让四级标题也显示

  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true