name: Deploy Hugo site to Pages

on:
  push:
    branches:
      - master  # 当 master 分支收到推送时触发

jobs:
  build-deploy:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true

      - name: Build
        run: hugo --minify

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public      # 将 public 目录的内容推送到 gh-pages 分支
          publish_branch: gh-pages    # 推送到 gh-pages 分支